### ISSUE TITLE
construction queue ui enhancements

### ISSUE THREAD

**Issue by ketzl** [DawnOfRevolution/DummyForBugs#10]
i see a little building and 24/50, and a snail and 2.44x.  can you add tooltips to both the building and the snail?  like "24/50 building spaces used. upgrade your city center to increase your available building space"   and "2.44x construction speed.  increase your workforce by building bungalows or employ naphthali crystals to magically speed up your workers"

 i'd like to be able to click on a building in the queue & have the map center on that building, with it selected

the 'x' cancel button, i'd like to see a tooltip when i hover over it saying the resource refund i'd get for cancelling.

**Comment by tejainece** [comment]
The first two issues are fixed.

I am creating a new issue for the 3rd issue.

Please post each issue its own issue item. So it is easy to track and fix.
