### ISSUE TITLE
Construction minister failed to start levelling up ironmongery 

### ISSUE THREAD

**Issue by Regal62** [DawnOfRevolution/DummyForBugs#102]
![screenshot_6](https://cloud.githubusercontent.com/assets/16354418/12073021/b83b32c4-b0b9-11e5-95c8-ca111bd6d888.png)
![screenshot_7](https://cloud.githubusercontent.com/assets/16354418/12073020/b837641e-b0b9-11e5-982e-e432332ed1b3.png)
I set the ironmongery and the timber mill  to a level 3 but it fail to level up either one.

**Comment by tejainece** [comment]
Fixed!
