### ISSUE TITLE
Don't allow two players with same names

### ISSUE THREAD

**Issue by Proxy49** [DawnOfRevolution/DummyForBugs#103]
Planetoid has a 0 score but has two cities. something is off here

**Comment by tejainece** [comment]
Planetoid only has 1 city.

**Comment by Proxy49** [comment]
he has two cities near me and he is listed twice in the rankings, his citiiess are 75:113 and 75:112

**Comment by Proxy49** [comment]
he has two cities near me and he is listed twice in the rankings, 
his citiiess are 75:113 and 75:112
