### ISSUE TITLE
build mini not building one city type

### ISSUE THREAD

**Issue by Proxy49** [DawnOfRevolution/DummyForBugs#112]
seem there is something screwy with the build minister. I have noticed that it will skip building one building  type while building up every thing else. for example I have one city here every building type is at L8 but one type is only L4 and one is only L2
![not building](https://cloud.githubusercontent.com/assets/16512871/12204730/ff64f528-b603-11e5-9d2f-7e15ee6ff27e.png)

**Comment by Quinn-Dexter** [comment]
check you minister see if you have all building types checked...  (i would like to see a check all check box there)

**Comment by Proxy49** [comment]
this tripped me up too. also some times you check something and 
the checkmark disappears. agree on the select all box

**Comment by tejainece** [comment]
Fixed!
