### ISSUE TITLE
Naphthali Crystals cannot be used

### ISSUE THREAD

**Issue by hxanthos** [DawnOfRevolution/DummyForBugs#118]
I have 17 Naphtali Crystals but it just stopped allowing me to use them. I see no issue with the limit...so wondering what's going on.

![naphthali crystal](https://cloud.githubusercontent.com/assets/16509872/12280246/bc9acc4a-b98c-11e5-9412-2fcb1353b899.jpg)

**Comment by tejainece** [comment]
I think used 10 Napthalli crystals in that city. You cannot use more than 10 in a city. That is the max. Have to display error message when this happens.

**Comment by hxanthos** [comment]
ah sorry, that must be it. I will set the issue as resolved.
