### ISSUE TITLE
City Center went from lvl7 to lvl8 in 10 secs

### ISSUE THREAD

**Issue by hxanthos** [DawnOfRevolution/DummyForBugs#120]
Same CS required some 1h for lvl6 to lvl7 for City Center but only 10sec for lvl7 to lvl8.
CS:15.02x

**Comment by tejainece** [comment]
Can let me know if this issue is still there? I think it is fixed.

**Comment by hxanthos** [comment]
Hi, i cannot test it again at the moment as i still don't have a second
city, but will possibly be able to test it within the next 2 days.

**Comment by hxanthos** [comment]
2nd city, with CS of 15.2x the City Center takes 1h6m to upgrade from lvl7 to lvl8. So the issue seems to be fixed as u said.
