### ISSUE TITLE
Construction time for items in the construction list won't update with the increase of CS from Bungalows in the list

### ISSUE THREAD

**Issue by hxanthos** [DawnOfRevolution/DummyForBugs#123]
As you can see in the picture below, with the upgrade of a Bungalow and the increase of CS, the time it takes to upgrade the other items in the list won't update accordingly, so although the CS is already increased by the time the items are to be constructed, it takes the same time as before the CS increase.
![cs](https://cloud.githubusercontent.com/assets/16509872/12380710/c5822f38-bd79-11e5-9bae-bf258ac8e186.jpg)

**Comment by hxanthos** [comment]
Update: Just noticed that the construction times appear screwed up anyway without any upgrade of bungalows...Same building time, from lvl1 to lvl2, sometimes takes 14secs and sometimes 10secs.

**Comment by tejainece** [comment]
Did you add the last Ironworks after the Bungalow built?

Building bungalow won't update the construction items already in the queue.

**Comment by hxanthos** [comment]
yeah although it should auto-update the building times every time a building finishes the upgrade, just as it readjusts the res output for example. However, the second incident i mention above, i added all the buildings at the same time with the same CS and with no Bungalow upgrading, and they took different times to finish...

**Comment by tejainece** [comment]
ok. Will look into it

**Comment by hxanthos** [comment]
i just noticed that the construction time of every item in the construction list gets re-evaluated with each increase in CS. Good job fixing that!

**Comment by tejainece** [comment]
Fixed
