### ISSUE TITLE
Gold remains the same after recruiting a Noble with Minister on to purify

### ISSUE THREAD

**Issue by hxanthos** [DawnOfRevolution/DummyForBugs#127]
Trade minister set to purify Gold excess over 165000 and Saltpeter excess over 100000 in the city.
Used items to increase the Gold in that city to 200000 and Saltpeter to 90000.
Recruited Noble which requires 165000 Gold & 85000 Saltpeter.

Saltpeter was deducted from my reserves, but Gold remained the same. Upon refresh, the Gold was reduced to 165000 with the difference to the amount I got with items been purified as the settings of the minister were set to do. 

So, no Gold was deducted for the recruitment of the Noble.

**Comment by tejainece** [comment]
Fixed
