### ISSUE TITLE
TradeIn never arrived

### ISSUE THREAD

**Issue by hxanthos** [DawnOfRevolution/DummyForBugs#128]
Check pic. TradeIn was supposed to arrive half an hour ago.
I am sending from a city who is attached to the receiving one. After i sent that trade manually since the trade mini wouldn't send the excess Food to the appointed city, i tried to send from a third city res to the same receiving city and no trade would go out. And now the one trade i managed to send is stuck.
![trade](https://cloud.githubusercontent.com/assets/16509872/12403629/74f71350-be35-11e5-8977-32e8a1e61868.jpg)

**Comment by hxanthos** [comment]
Just noticed there is a second trade from the same sending to the same receiving that is also late and never appeared in the receiving city.
![trade 2](https://cloud.githubusercontent.com/assets/16509872/12403806/cbf3481c-be36-11e5-93f7-fed1ce41eb94.jpg)

**Comment by tejainece** [comment]
Whats your in-game name?

**Comment by hxanthos** [comment]
4Eigner

for the last 2 days no trade arrives actually so i stopped the trade mini in all my cities

**Comment by tejainece** [comment]
will fix it
