### ISSUE TITLE
New buildings allowed over the building limit

### ISSUE THREAD

**Issue by hxanthos** [DawnOfRevolution/DummyForBugs#129]
Buildings added in the construction queue before final upgrade to lvl10 Centre are allowed to be built and don't count against the limit set. For example, my city now has 94 buildings with 90 technically allowed. Will update once i upgrade to lvl10 and check if they count towards the total amount of buildings allowed in the city.
![building queue](https://cloud.githubusercontent.com/assets/16509872/12413097/92b8cba2-be8c-11e5-88d0-67213978a1b5.jpg)

**Comment by hxanthos** [comment]
Update: although they take resources and time to be built, the buildings over the limit appear for a few seconds and then disappear again so the limit is corrected. However, the res and time is gone.

**Comment by tejainece** [comment]
It is fixed.
