### ISSUE TITLE
Unknown Error. Contact any of the GMs!

### ISSUE THREAD

**Issue by hxanthos** [DawnOfRevolution/DummyForBugs#130]
The city has been stuck like this for the last 8h or so. No building, no downgrading, no sending out res, wood and iron are stuck full by themselves..
![contact any of the gms](https://cloud.githubusercontent.com/assets/16509872/12429482/bed40dec-beea-11e5-951a-58b30fcb066c.png)

**Comment by tejainece** [comment]
Which city is this? is it still stuck?

**Comment by hxanthos** [comment]
city "09" and no it's finally moving! thanks!
Although the Res (Wood & Iron) is still always full while buildings take res away to upgrade.

**Comment by hxanthos** [comment]
It is stuck again.

**Comment by tejainece** [comment]
Working on that issue.

**Comment by hxanthos** [comment]
no more issues with this city or any other new city since. Thanks for fixing it. You can close this thread.
