### ISSUE TITLE
Sending way too much gold to hub 

### ISSUE THREAD

**Issue by 1Sneaky** [DawnOfRevolution/DummyForBugs#132]
I have 8 trades to the hub, all approximately 128k gold each  storage in this city is 417k   this is not possible especially as there is still 330k in storage ???  
![2016-01-20](https://cloud.githubusercontent.com/assets/16788877/12437717/f75c9d10-bf6b-11e5-8c9a-91bc7063a266.png)

**Comment by tejainece** [comment]
Fixed
