### ISSUE TITLE
New City appear in the purification menu but not in the drop down list for cities

### ISSUE THREAD

**Issue by hxanthos** [DawnOfRevolution/DummyForBugs#135]
As u can see in the pics, a "New City" appears in the purification list, but not in my drop down city menu, so i cannot access it from there, although i can see it in the Region View and access it by clicking on it there.
![city](https://cloud.githubusercontent.com/assets/16509872/12525843/f79db694-c167-11e5-8ab2-75873dc6f95c.jpg)
![city 2](https://cloud.githubusercontent.com/assets/16509872/12525842/f79da9ba-c167-11e5-88e5-9e9b49594be5.jpg)

**Comment by hxanthos** [comment]
this city is since 12h stuck as the "09" before.

**Comment by tejainece** [comment]
are you available on skype?

**Comment by hxanthos** [comment]
mailed u my skype name
