### ISSUE TITLE
Zooming out causes alignment issues with pop-up menu

### ISSUE THREAD

**Issue by j4nr6n** [DawnOfRevolution/DummyForBugs#42]
When you zoom out on the map is causes the menu that pops up when you click on a node to be mis-aligned.

**Comment by tejainece** [comment]
This is an annoying know issue. Will have to fix this soon. Just not up on the priority list.

**Comment by cleverca22** [comment]
zoom also doesn't keep the map centered properly, and can leave you panned way off the map

the background image(grass) doesnt scale with the zoom, causing things to look weird as you zoom in/out

the buttons around a selected building dont scale with zoom

**Comment by tejainece** [comment]
Fixed!
