### ISSUE TITLE
No time...

### ISSUE THREAD

**Issue by j4nr6n** [DawnOfRevolution/DummyForBugs#47]
There is no time anywhere that I can find. I can't coordinate my devastating attacks on KnightsOT...

This is a sad day :cry:

**Comment by tejainece** [comment]
Haha. Timed attacks are not implemented yet.

Attack is a new feature, implemented last week. Untested. I am testing it this week. Let me know if you find issues with attacks.

**Comment by tejainece** [comment]
By the that would end up devastating for you, KnightsOT is me ;P
