### ISSUE TITLE
What's going on here?

### ISSUE THREAD

**Issue by j4nr6n** [DawnOfRevolution/DummyForBugs#49]
![screenshot from 2015-08-31 20 12 06](https://cloud.githubusercontent.com/assets/3661151/9593456/9db2be48-501c-11e5-9340-5efcf7d7f0c3.png)

**Comment by tejainece** [comment]
There is actually a resource node there. Might be oil field or ruins. Probably oil field. Don't have any graphics for that. Will put some place holder though.

**Comment by cleverca22** [comment]
ran into the same issue above a strip of 'bat caves'

**Comment by tejainece** [comment]
Fixed
