### ISSUE TITLE
Townhall construction times

### ISSUE THREAD

**Issue by RoyalBee1** [DawnOfRevolution/DummyForBugs#5]
I am upgrading the townhall from level 6 to level 7. The total time required in the construction queue is 21:51:45 but the time to upgrade in the townhall description is 6:43:0

Maybe I clicked on it several times and it added in additional time? But, the total time is not a multiple of the time in the townhall description. Maybe it includes some construction speed adjustment.

**Comment by tejainece** [comment]
21:51:45 should be time when it finishes. 6:43:0 should be how long it takes to build. 21:51:45 doesn't exactly show correct local or server time yet. Will fix it.
