### ISSUE TITLE
I'm supporting myself with nothing...

### ISSUE THREAD

**Issue by j4nr6n** [DawnOfRevolution/DummyForBugs#50]
![screenshot from 2015-08-31 20 20 06](https://cloud.githubusercontent.com/assets/3661151/9593540/c96666e2-501d-11e5-85ba-7dfcaeed9da5.png)
I guess it must be emotional support.

I don't have any troops aside from conscripts. When I click on the button on my city and then click support, nothing happens (or so I thought, until I went back into city view.)

**Comment by j4nr6n** [comment]
Can also support Ketzele with 50k nothings... :smiley: 
![screenshot from 2015-08-31 20 26 25](https://cloud.githubusercontent.com/assets/3661151/9593601/9e6beb78-501e-11e5-8952-2d5c6b77ddc4.png)

**Comment by tejainece** [comment]
Ok. Fixed it in my version. Not pushed to server yet.

Haven't implemented minimum troops for plunder, assault and siege though.

**Comment by tejainece** [comment]
Minimum troops requirement is implemented too
