### ISSUE TITLE
Recruiting Negative amounts of troops

### ISSUE THREAD

**Issue by Emperor1** [DawnOfRevolution/DummyForBugs#60]
I am able to recruit negative amounts of troops.  Strangely I have to use the ranger fields to recruit the zerk dudes.  Anyway I am able to recruit any negative amount of troop.   I can also use a decimal point and it will recruit 0 troops at a time.  There may be other mathematical symbols that can be used in those fields as well.  I would caution that even when these sysmbols such as negative cannot be used a simple copy and paste can enter undesired elements into the fields.  Even when that function is disabled a player may be able to highlight any number on the screen and drag and drop that number into any field.

**Comment by tejainece** [comment]
Fixed!
