### ISSUE TITLE
gold

### ISSUE THREAD

**Issue by MasterGuruThom** [DawnOfRevolution/DummyForBugs#67]
got markets but no gold coming in really need gold now

**Comment by tejainece** [comment]
I just checked your city. Seems to have 3 markets, and producing 12 gold/hr (4/hr each).

But i agree the production of gold is slow.

**Comment by MasterGuruThom** [comment]
got areodrome now 2 of them there gold count isnt being added to overall production

**Comment by tejainece** [comment]
Fixed!
