### ISSUE TITLE
Troops are bogo!

### ISSUE THREAD

**Issue by j4nr6n** [DawnOfRevolution/DummyForBugs#71]
Well really they are buy any amount for the price of one.

Here's what I mean:

When I recruit 200 musketeers or 1000 or as many as I can hold in my baracks, only the cost of the first unit is deducted from my stockpile. 200 musketeers is 35k ish coal and only 150 is taken from my storage.

So basically you pay for the first one and get the rest free.

**Comment by tejainece** [comment]
Fixed
