### ISSUE TITLE
Some tooltips are offscreen

### ISSUE THREAD

**Issue by Emoir** [DawnOfRevolution/DummyForBugs#77]
When you have clicked on a empty city spot, the tooltips for the Artillery Yard, Shipyard, Sky Dock and Star Fort are mostly offscreen.

Pictures:

http://puu.sh/lZF7o/15b8f713ad.jpg
http://puu.sh/lZF6u/9b376d1a30.jpg
http://puu.sh/lZF5y/4697e98c7f.jpg
http://puu.sh/lZF4J/647285b3a6.jpg

**Comment by tejainece** [comment]
Fixed!
