### ISSUE TITLE
Deletion of Buildings

### ISSUE THREAD

**Issue by Regal62** [DawnOfRevolution/DummyForBugs#80]
The buildings are very close to one another and there are times when you are mouse clicking one building you are actually clicking the deletion button. I would like to suggest that you have a pop up box that asks the player if they want to delete  yes or no or arrange the deletion button in such a way that it is not so easy for the player to mistakenly click it

**Comment by Quinn-Dexter** [comment]
this happens because the buttons dont shrink the same % as the rest of the display when you zoom out, so they start overlaping next tile the smaller you have the display

**Comment by Regal62** [comment]
This issue has be resolved by the use of a pop up indicating the demolish function
