### ISSUE TITLE
building list panel only appears in zoomed-in view

### ISSUE THREAD

**Issue by zaphod717** [DawnOfRevolution/DummyForBugs#91]
Yeah when I zoom out [with the mouse wheel] and click on the city map, the building list panel doesn't appear. when I zoom back out, it does, after I click again
NealSchmidt

OK, it looks like I misinterpreted what was happening. if I click on other locations, the buildings panel appears. not clear why some spots it doesn't.

**Comment by tejainece** [comment]
it was because ruins had no image. So they are seen as empty spots. Fixed it.

Thanks.
