### ISSUE TITLE
Sticky mouse

### ISSUE THREAD

**Issue by Regal62** [DawnOfRevolution/DummyForBugs#92]
There are times when I move the city and/or region view that the view will stick to my mouse and won't release until I hit (esc) or I click the view. If I click on the view then the building menu pops with the circle locator.  This is most annoying because then you need to hit the (esc) button to clear it from the screen. There are times it won't release I have to refresh the game.
This issue is one of the most annoying bugs to deal with.

**Comment by tejainece** [comment]
Fixed!

**Comment by Regal62** [comment]
In which version did you fix it ? This is still happening in the current version and it now requires me to constantly refresh ...grrrrr
